POST http://192.168.0.104:3000/authData HTTP/1.1
content-type: application/json


{
    "Name":"Archit",
    "Email":"arcyjain2002@gmail.com",
    "PhotoUrl":"http://example.com",
    "TodoList":[{
        "text":"abcde",
        "key":"hello"
    }]
    
}

###
POST http://192.168.0.104:3000/authData HTTP/1.1
content-type: application/json


{
    "Name":"John",
    "Email":"xyz@example",
    "PhotoUrl":"http://example2.com",
    "TodoList":[{
        "text":"abcde",
        "val":"hello"
    }]
    
}

###
POST http://192.168.0.104:3000/todoDelete HTTP/1.1
content-type: application/json

{
    "Name":"Archit",
    "Email":"arcyjain2002@gmail.com",
    "PhotoUrl":"http://example.com",
    "val":"hello"
}

###
POST http://192.168.0.104:3000/todoUpdate HTTP/1.1
content-type: application/json

{
    "Email":"arcyjain2002@gmail.com",
    "key":"123",
    "text":"todo1"
}

###
GET http://192.168.0.104:3000/getTodo?Email=arcyjain2002@gmail.com HTTP/1.1
content-type: application/json

# {
#     "Email":"arcyjain2002@gmail.com",
#     "val":"123",
#     "text":"todo1"
# }

